server:
  port: 8111

spring:
  main:
    allow-circular-references: true
  application:
    name: CMS-Auth-Service

  datasource:
    url: jdbc:mysql://b6060dfffd3b4a:4deab34a@us-cdbr-east-06.cleardb.net/heroku_58fbec60b723d43?reconnect=true
#    username: root
#    password: Dev@#$123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update



eureka:
  client:
    serviceUrl:
      defaultZone: https://cms-discovery.herokuapp.com/eureka
  instance:
    preferIpAddress: true



  main:
    allow-circular-references: true

jwt:
  secretKey:
    name: ${SECRET_KEY:secretKey}


