server:
  port: 8111
  servlet:
    context-path: /user

spring:
  main:
    allow-circular-references: true
  application:
    name: CMS-Auth-Service
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: ${DB_URL:jdbc:mysql://43.205.229.17:3306/cms_auth}
    username: ${DB_USERNAME:user}
    password: ${DB_PASSWORD:Dev@#$123}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update

springdoc:
  show-login-endpoint: true

eureka:
  client:
    serviceUrl:
      defaultZone: ${DEFAULT_ZONE:http://ec2-65-2-131-246.ap-south-1.compute.amazonaws.com:8761/eureka}
  instance:
    preferIpAddress: true


security:
  key: accessKey


logging:
  level:
    com.cms.auth: ${LOG_LEVEL:DEBUG}
  file:
    path: ${LOGPATH:./log}


