server:
  port: 8111

spring:
  application:
    name: CMS-Auth-Service

  datasource:
    url: jdbc:mysql://localhost:3306/cms_auth
    username: root
    password: Dev@#$123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update


  main:
    allow-circular-references: true

jwt:
  secretKey:
    name: ${SECRET_KEY:secretKey}


